/* THIS FILE IS PART OF CODEC MESSAGE PROJECT ABOUT 3GPP 36.331
 * beam_management_ssb_csi_rs.h - this is the header file for message: BeamManagementSSB-CSI-RS
 *
 * THIS PROGRAM IS NOT FREE SOFTWARE.
 * YOU SHOULD HAVE RECEIVED A COPY OF LICENSE FROM BINXIAN DUAN, IF NOT, THE BEHAVIOR IS TORT!
 * Copyright (c) 2018 Binxian Duan <binxd@126.com>. All rights reserved.
 */
#ifndef _BEAM_MANAGEMENT_SSB_CSI_RS_H_
#define _BEAM_MANAGEMENT_SSB_CSI_RS_H_

#include "types.h"
#include "contants.h" 				
#include "handle_bits.h"


typedef enum {
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCEONETX_N8,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCEONETX_N16,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCEONETX_N32,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCEONETX_N64,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCEONETX_max = 0x7FFFFFFF
}BeamManagementSSB_CSI_RS_maxNumberSSB_CSI_RS_ResourceOneTx_e;


typedef enum {
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N0,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N4,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N8,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N16,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N32,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_N64,
	BEAMMANAGEMENTSSB_CSI_RS_MAXNUMBERSSB_CSI_RS_RESOURCETWOTX_max = 0x7FFFFFFF
}BeamManagementSSB_CSI_RS_maxNumberSSB_CSI_RS_ResourceTwoTx_e;


typedef enum {
	BEAMMANAGEMENTSSB_CSI_RS_SUPPORTEDCSI_RS_DENSITY_ONE,
	BEAMMANAGEMENTSSB_CSI_RS_SUPPORTEDCSI_RS_DENSITY_THREE,
	BEAMMANAGEMENTSSB_CSI_RS_SUPPORTEDCSI_RS_DENSITY_ONEANDTHREE,
	BEAMMANAGEMENTSSB_CSI_RS_SUPPORTEDCSI_RS_DENSITY_max = 0x7FFFFFFF
}BeamManagementSSB_CSI_RS_supportedCSI_RS_Density_e;


typedef struct {
	BeamManagementSSB_CSI_RS_maxNumberSSB_CSI_RS_ResourceOneTx_e       maxNumberSSB_CSI_RS_ResourceOneTx;
	BeamManagementSSB_CSI_RS_maxNumberSSB_CSI_RS_ResourceTwoTx_e       maxNumberSSB_CSI_RS_ResourceTwoTx;
	BeamManagementSSB_CSI_RS_supportedCSI_RS_Density_e                 supportedCSI_RS_Density;
}BeamManagementSSB_CSI_RS_t;


extern void EncodeBeamManagementSSB_CSI_RS(
	BeamManagementSSB_CSI_RS_t *i_encoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);
extern void DecodeBeamManagementSSB_CSI_RS(
	BeamManagementSSB_CSI_RS_t *o_decoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);

#endif
