/* THIS FILE IS PART OF CODEC MESSAGE PROJECT ABOUT 3GPP 36.331
 * poll_byte.h - this is the header file for message: PollByte
 *
 * THIS PROGRAM IS NOT FREE SOFTWARE.
 * YOU SHOULD HAVE RECEIVED A COPY OF LICENSE FROM BINXIAN DUAN, IF NOT, THE BEHAVIOR IS TORT!
 * Copyright (c) 2018 Binxian Duan <binxd@126.com>. All rights reserved.
 */
#ifndef _POLL_BYTE_H_
#define _POLL_BYTE_H_

#include "types.h"
#include "contants.h" 				
#include "handle_bits.h"


typedef enum {
	POLLBYTE_KB1,
	POLLBYTE_KB2,
	POLLBYTE_KB5,
	POLLBYTE_KB8,
	POLLBYTE_KB10,
	POLLBYTE_KB15,
	POLLBYTE_KB25,
	POLLBYTE_KB50,
	POLLBYTE_KB75,
	POLLBYTE_KB100,
	POLLBYTE_KB125,
	POLLBYTE_KB250,
	POLLBYTE_KB375,
	POLLBYTE_KB500,
	POLLBYTE_KB750,
	POLLBYTE_KB1000,
	POLLBYTE_KB1250,
	POLLBYTE_KB1500,
	POLLBYTE_KB2000,
	POLLBYTE_KB3000,
	POLLBYTE_KB4000,
	POLLBYTE_KB4500,
	POLLBYTE_KB5000,
	POLLBYTE_KB5500,
	POLLBYTE_KB6000,
	POLLBYTE_KB6500,
	POLLBYTE_KB7000,
	POLLBYTE_KB7500,
	POLLBYTE_MB8,
	POLLBYTE_MB9,
	POLLBYTE_MB10,
	POLLBYTE_MB11,
	POLLBYTE_MB12,
	POLLBYTE_MB13,
	POLLBYTE_MB14,
	POLLBYTE_MB15,
	POLLBYTE_MB16,
	POLLBYTE_MB17,
	POLLBYTE_MB18,
	POLLBYTE_MB20,
	POLLBYTE_MB25,
	POLLBYTE_MB30,
	POLLBYTE_MB40,
	POLLBYTE_INFINITY,
	POLLBYTE_SPARE20,
	POLLBYTE_SPARE19,
	POLLBYTE_SPARE18,
	POLLBYTE_SPARE17,
	POLLBYTE_SPARE16,
	POLLBYTE_SPARE15,
	POLLBYTE_SPARE14,
	POLLBYTE_SPARE13,
	POLLBYTE_SPARE12,
	POLLBYTE_SPARE11,
	POLLBYTE_SPARE10,
	POLLBYTE_SPARE9,
	POLLBYTE_SPARE8,
	POLLBYTE_SPARE7,
	POLLBYTE_SPARE6,
	POLLBYTE_SPARE5,
	POLLBYTE_SPARE4,
	POLLBYTE_SPARE3,
	POLLBYTE_SPARE2,
	POLLBYTE_SPARE1,
	POLLBYTE_max = 0x7FFFFFFF
}PollByte_e;


extern void EncodePollByte(
	PollByte_e i_encoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);
extern void DecodePollByte(
	PollByte_e *o_decoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);

#endif
