/* THIS FILE IS PART OF CODEC MESSAGE PROJECT ABOUT 3GPP 36.331
 * t_poll_retransmit.h - this is the header file for message: T-PollRetransmit
 *
 * THIS PROGRAM IS NOT FREE SOFTWARE.
 * YOU SHOULD HAVE RECEIVED A COPY OF LICENSE FROM BINXIAN DUAN, IF NOT, THE BEHAVIOR IS TORT!
 * Copyright (c) 2018 Binxian Duan <binxd@126.com>. All rights reserved.
 */
#ifndef _T_POLL_RETRANSMIT_H_
#define _T_POLL_RETRANSMIT_H_

#include "types.h"
#include "contants.h" 				
#include "handle_bits.h"


typedef enum {
	T_POLLRETRANSMIT_MS5,
	T_POLLRETRANSMIT_MS10,
	T_POLLRETRANSMIT_MS15,
	T_POLLRETRANSMIT_MS20,
	T_POLLRETRANSMIT_MS25,
	T_POLLRETRANSMIT_MS30,
	T_POLLRETRANSMIT_MS35,
	T_POLLRETRANSMIT_MS40,
	T_POLLRETRANSMIT_MS45,
	T_POLLRETRANSMIT_MS50,
	T_POLLRETRANSMIT_MS55,
	T_POLLRETRANSMIT_MS60,
	T_POLLRETRANSMIT_MS65,
	T_POLLRETRANSMIT_MS70,
	T_POLLRETRANSMIT_MS75,
	T_POLLRETRANSMIT_MS80,
	T_POLLRETRANSMIT_MS85,
	T_POLLRETRANSMIT_MS90,
	T_POLLRETRANSMIT_MS95,
	T_POLLRETRANSMIT_MS100,
	T_POLLRETRANSMIT_MS105,
	T_POLLRETRANSMIT_MS110,
	T_POLLRETRANSMIT_MS115,
	T_POLLRETRANSMIT_MS120,
	T_POLLRETRANSMIT_MS125,
	T_POLLRETRANSMIT_MS130,
	T_POLLRETRANSMIT_MS135,
	T_POLLRETRANSMIT_MS140,
	T_POLLRETRANSMIT_MS145,
	T_POLLRETRANSMIT_MS150,
	T_POLLRETRANSMIT_MS155,
	T_POLLRETRANSMIT_MS160,
	T_POLLRETRANSMIT_MS165,
	T_POLLRETRANSMIT_MS170,
	T_POLLRETRANSMIT_MS175,
	T_POLLRETRANSMIT_MS180,
	T_POLLRETRANSMIT_MS185,
	T_POLLRETRANSMIT_MS190,
	T_POLLRETRANSMIT_MS195,
	T_POLLRETRANSMIT_MS200,
	T_POLLRETRANSMIT_MS205,
	T_POLLRETRANSMIT_MS210,
	T_POLLRETRANSMIT_MS215,
	T_POLLRETRANSMIT_MS220,
	T_POLLRETRANSMIT_MS225,
	T_POLLRETRANSMIT_MS230,
	T_POLLRETRANSMIT_MS235,
	T_POLLRETRANSMIT_MS240,
	T_POLLRETRANSMIT_MS245,
	T_POLLRETRANSMIT_MS250,
	T_POLLRETRANSMIT_MS300,
	T_POLLRETRANSMIT_MS350,
	T_POLLRETRANSMIT_MS400,
	T_POLLRETRANSMIT_MS450,
	T_POLLRETRANSMIT_MS500,
	T_POLLRETRANSMIT_MS800,
	T_POLLRETRANSMIT_MS1000,
	T_POLLRETRANSMIT_MS2000,
	T_POLLRETRANSMIT_MS4000,
	T_POLLRETRANSMIT_SPARE5,
	T_POLLRETRANSMIT_SPARE4,
	T_POLLRETRANSMIT_SPARE3,
	T_POLLRETRANSMIT_SPARE2,
	T_POLLRETRANSMIT_SPARE1,
	T_POLLRETRANSMIT_max = 0x7FFFFFFF
}T_PollRetransmit_e;


extern void EncodeT_PollRetransmit(
	T_PollRetransmit_e i_encoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);
extern void DecodeT_PollRetransmit(
	T_PollRetransmit_e *o_decoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);

#endif
