/* THIS FILE IS PART OF CODEC MESSAGE PROJECT ABOUT 3GPP 36.331
 * t_status_prohibit.h - this is the header file for message: T-StatusProhibit
 *
 * THIS PROGRAM IS NOT FREE SOFTWARE.
 * YOU SHOULD HAVE RECEIVED A COPY OF LICENSE FROM BINXIAN DUAN, IF NOT, THE BEHAVIOR IS TORT!
 * Copyright (c) 2018 Binxian Duan <binxd@126.com>. All rights reserved.
 */
#ifndef _T_STATUS_PROHIBIT_H_
#define _T_STATUS_PROHIBIT_H_

#include "types.h"
#include "contants.h" 				
#include "handle_bits.h"


typedef enum {
	T_STATUSPROHIBIT_MS0,
	T_STATUSPROHIBIT_MS5,
	T_STATUSPROHIBIT_MS10,
	T_STATUSPROHIBIT_MS15,
	T_STATUSPROHIBIT_MS20,
	T_STATUSPROHIBIT_MS25,
	T_STATUSPROHIBIT_MS30,
	T_STATUSPROHIBIT_MS35,
	T_STATUSPROHIBIT_MS40,
	T_STATUSPROHIBIT_MS45,
	T_STATUSPROHIBIT_MS50,
	T_STATUSPROHIBIT_MS55,
	T_STATUSPROHIBIT_MS60,
	T_STATUSPROHIBIT_MS65,
	T_STATUSPROHIBIT_MS70,
	T_STATUSPROHIBIT_MS75,
	T_STATUSPROHIBIT_MS80,
	T_STATUSPROHIBIT_MS85,
	T_STATUSPROHIBIT_MS90,
	T_STATUSPROHIBIT_MS95,
	T_STATUSPROHIBIT_MS100,
	T_STATUSPROHIBIT_MS105,
	T_STATUSPROHIBIT_MS110,
	T_STATUSPROHIBIT_MS115,
	T_STATUSPROHIBIT_MS120,
	T_STATUSPROHIBIT_MS125,
	T_STATUSPROHIBIT_MS130,
	T_STATUSPROHIBIT_MS135,
	T_STATUSPROHIBIT_MS140,
	T_STATUSPROHIBIT_MS145,
	T_STATUSPROHIBIT_MS150,
	T_STATUSPROHIBIT_MS155,
	T_STATUSPROHIBIT_MS160,
	T_STATUSPROHIBIT_MS165,
	T_STATUSPROHIBIT_MS170,
	T_STATUSPROHIBIT_MS175,
	T_STATUSPROHIBIT_MS180,
	T_STATUSPROHIBIT_MS185,
	T_STATUSPROHIBIT_MS190,
	T_STATUSPROHIBIT_MS195,
	T_STATUSPROHIBIT_MS200,
	T_STATUSPROHIBIT_MS205,
	T_STATUSPROHIBIT_MS210,
	T_STATUSPROHIBIT_MS215,
	T_STATUSPROHIBIT_MS220,
	T_STATUSPROHIBIT_MS225,
	T_STATUSPROHIBIT_MS230,
	T_STATUSPROHIBIT_MS235,
	T_STATUSPROHIBIT_MS240,
	T_STATUSPROHIBIT_MS245,
	T_STATUSPROHIBIT_MS250,
	T_STATUSPROHIBIT_MS300,
	T_STATUSPROHIBIT_MS350,
	T_STATUSPROHIBIT_MS400,
	T_STATUSPROHIBIT_MS450,
	T_STATUSPROHIBIT_MS500,
	T_STATUSPROHIBIT_MS800,
	T_STATUSPROHIBIT_MS1000,
	T_STATUSPROHIBIT_MS1200,
	T_STATUSPROHIBIT_MS1600,
	T_STATUSPROHIBIT_MS2000,
	T_STATUSPROHIBIT_MS2400,
	T_STATUSPROHIBIT_SPARE2,
	T_STATUSPROHIBIT_SPARE1,
	T_STATUSPROHIBIT_max = 0x7FFFFFFF
}T_StatusProhibit_e;


extern void EncodeT_StatusProhibit(
	T_StatusProhibit_e i_encoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);
extern void DecodeT_StatusProhibit(
	T_StatusProhibit_e *o_decoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);

#endif
