/* THIS FILE IS PART OF CODEC MESSAGE PROJECT ABOUT 3GPP 36.331
 * ul_data_split_threshold.h - this is the header file for message: UL-DataSplitThreshold
 *
 * THIS PROGRAM IS NOT FREE SOFTWARE.
 * YOU SHOULD HAVE RECEIVED A COPY OF LICENSE FROM BINXIAN DUAN, IF NOT, THE BEHAVIOR IS TORT!
 * Copyright (c) 2018 Binxian Duan <binxd@126.com>. All rights reserved.
 */
#ifndef _UL_DATA_SPLIT_THRESHOLD_H_
#define _UL_DATA_SPLIT_THRESHOLD_H_

#include "types.h"
#include "contants.h" 				
#include "handle_bits.h"


typedef enum {
	UL_DATASPLITTHRESHOLD_B0,
	UL_DATASPLITTHRESHOLD_B100,
	UL_DATASPLITTHRESHOLD_B200,
	UL_DATASPLITTHRESHOLD_B400,
	UL_DATASPLITTHRESHOLD_B800,
	UL_DATASPLITTHRESHOLD_B1600,
	UL_DATASPLITTHRESHOLD_B3200,
	UL_DATASPLITTHRESHOLD_B6400,
	UL_DATASPLITTHRESHOLD_B12800,
	UL_DATASPLITTHRESHOLD_B25600,
	UL_DATASPLITTHRESHOLD_B51200,
	UL_DATASPLITTHRESHOLD_B102400,
	UL_DATASPLITTHRESHOLD_B204800,
	UL_DATASPLITTHRESHOLD_B409600,
	UL_DATASPLITTHRESHOLD_B819200,
	UL_DATASPLITTHRESHOLD_B1228800,
	UL_DATASPLITTHRESHOLD_B1638400,
	UL_DATASPLITTHRESHOLD_B2457600,
	UL_DATASPLITTHRESHOLD_B3276800,
	UL_DATASPLITTHRESHOLD_B4096000,
	UL_DATASPLITTHRESHOLD_B4915200,
	UL_DATASPLITTHRESHOLD_B5734400,
	UL_DATASPLITTHRESHOLD_B6553600,
	UL_DATASPLITTHRESHOLD_INFINITY,
	UL_DATASPLITTHRESHOLD_SPARE8,
	UL_DATASPLITTHRESHOLD_SPARE7,
	UL_DATASPLITTHRESHOLD_SPARE6,
	UL_DATASPLITTHRESHOLD_SPARE5,
	UL_DATASPLITTHRESHOLD_SPARE4,
	UL_DATASPLITTHRESHOLD_SPARE3,
	UL_DATASPLITTHRESHOLD_SPARE2,
	UL_DATASPLITTHRESHOLD_SPARE1,
	UL_DATASPLITTHRESHOLD_max = 0x7FFFFFFF
}UL_DataSplitThreshold_e;


extern void EncodeUL_DataSplitThreshold(
	UL_DataSplitThreshold_e i_encoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);
extern void DecodeUL_DataSplitThreshold(
	UL_DataSplitThreshold_e *o_decoded_field, 
	uint8 *buff, 
	BitsIter *bits_iter, 
	void *asn_error);

#endif
